# Generated by Django 4.2.4 on 2023-09-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_card',
            new_name='postal_code',
        ),
    ]
